require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'app/controllers/frontend/templates_controller.rb'

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 194
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Max: 26

Metrics/ClassLength:
  Enabled: false
  Max: 152

Lint/NonAtomicFileOperation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Security/Eval:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/PredicateName:
  Enabled: false


Style/MultilineBlockChain:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/UnreachableCode:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Naming/MethodName:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false


Naming/VariableNumber:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/TransactionExitStatement:
  Enabled: false
Rails/ReversibleMigration:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/RenderInline:
  Enabled: false
Rails/ActionControllerTestCase:
  Enabled: false