#inherit_from: ../.rubocop.yml
AllCops:
  NewCops: enable

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 194

Metrics/BlockLength:
  Enabled: false
  Max: 26

Metrics/ClassLength:
  Enabled: false
  Max: 152

Lint/NonAtomicFileOperation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

