version: '3.4'
services:
  concerto:
    image: concerto-development
    container_name: concerto-dev
    command: bin/rails server --port=3000 --binding=0.0.0.0
    environment:
      - RAILS_ENV=development
    ports:
      - "3210:3000" # don't do this on production!
    volumes:
      - .:/rails  # use app files from host
      - /rails/node_modules # but not the node_modules!
      - ./docker-container-mounts/tmp:/rails/tmp
      - ./docker-container-mounts/storage:/rails/storage
    restart: "no"
