# syntax = docker/dockerfile:1

FROM concerto-stage1 as concerto-stage2

# Copy application code
COPY . .

# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
# Precompile bootsnap code for faster boot times

RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile && \
    bundle exec bootsnap precompile app/ lib/ && \
    bin/rails db:migrate && \
    bin/rails db:seed
