# deactivated in boot.rb - tbd: can be deleted?
automatic_bundle_installation: true
automatic_database_installation: true
compile_production_assets: true
#bundle_install_options: "--path vendor/bundle"
